### ISSUE TITLE
Electron App Compatability

### ISSUE THREAD

**Issue by john1234brown** [JacobLinCool/node-cloudflared#16]
So im building a electron application and i have been stumped with having to somewhat update this module to be compatible with it i would like to give out this code to you freely as i hope you will update and include it as it is quite useful!

basically your constants.js file just needs to be updated to do the following to support electron apps because the binary isnt executable from within the asar compressed file so we must unpackage it if the application is running with an app.asar and use the extracted location as the binary path here is what it would look like 

```javascript
import import_node_path from 'node:path';
import { promises as fsPromises, constants } from 'node:fs';
import { execFile } from 'node:child_process';

const binName = process.platform === "win32" ? "cloudflared.exe" : "cloudflared";
const binPathInAsar = import_node_path.join(__dirname, "..", "bin", binName);

// Create a temporary directory to extract the binary
const tempDir = import_node_path.join(process.resourcesPath, 'temp');
const extractedBinPath = import_node_path.join(tempDir, binName);

async function extractBinary() {
  try {
    // Ensure the temporary directory exists
    await fsPromises.mkdir(tempDir, { recursive: true });

    // Check if the binary already exists in the temporary directory
    const exists = await fsPromises.access(extractedBinPath, constants.F_OK)
      .then(() => true)
      .catch(() => false);

    if (!exists) {
      // Copy the binary to the temporary directory
      await fsPromises.copyFile(binPathInAsar, extractedBinPath);

      // Ensure executable permissions for the extracted binary
      await fsPromises.chmod(extractedBinPath, 0o755);
    }

    return extractedBinPath;
  } catch (error) {
    console.error('Error extracting or setting permissions for the binary:', error);
    return null;
  }
}

async function executeBinary() {
  try {
    const extractedPath = await extractBinary();
    
    if (extractedPath) {
      console.log('Binary extracted to:', extractedPath);

      // Example: Execute Cloudflared binary
      execFile(extractedPath, ['--version'], (error, stdout, stderr) => {
        if (error) {
          console.error('Error executing binary:', error);
          return;
        }
        console.log('Cloudflared version:', stdout.trim());
      });

      // Dynamically update the bin variable to the extracted path
      bin = extractedPath;
      console.log('Updated bin path to:', bin);
    }
  } catch (error) {
    console.error('Error executing binary:', error);
  }
}

// Initial bin variable (before extraction)
let bin = binPathInAsar;
console.log('Initial bin path:', bin);

executeBinary();

const CLOUDFLARED_VERSION = process.env.CLOUDFLARED_VERSION || "latest";
const RELEASE_BASE = "https://github.com/cloudflare/cloudflared/releases/";

export {
  CLOUDFLARED_VERSION,
  RELEASE_BASE,
  bin
};
```

you will have to restructure some of this to be both cjm and esm compatable but yeah this is just about how it can be solved honestly probably dont need to execute the permission change just extract the file to tmp directory so its executable please and thank you very much for your time and consideration on this btw.

**Comment by john1234brown** [comment]
Also Here is a far easier method then needing to actually move the file!
instead utilizing the constant.js to update the bin location you can do this i have currently ported a few files from your module into my electron application to actually get it to work just fine but i had to do the following
![image](https://github.com/JacobLinCool/node-cloudflared/assets/8825800/516f53c2-4c51-49a8-8080-add6f3968b27)
```javascript

const binName = process.platform === "win32" ? "cloudflared.exe" : (process.platform === "darwin" ? "maccloudflared" : "cloudflared");
const bin = import_node_path.default.join(__dirname, "..", "..", "..", "bin", binName);
console.log('Bin path is:', bin);
```
I just done this made it set to store the bin file in the main root folder under bin folder inside the root folder of the electron application so i could bundle it with the app and make it executable so just had to include the tunnel.js file and regex.js file to get it to work

So if you could use that app.asar detection to somehow make it be installed in a bin folder like this style would be a whole lot easier then needing to move it and such etc..!
Also my application uses merkle verification so i need all three binarys to be in it so no matter the os its generates the same merkle! all though it might be wasted space but ehhh! thank you for an amazing public source code btw glad i was able to solve this on my own actually!

**Comment by JacobLinCool** [comment]
It seems very useful for Electron use cases. Thank you for sharing your solution!

Would it be helpful if `bin` respected an environment variable such as `CLOUDFLARED_BIN`, or if there was a function to set it?

For example:
```ts
export const bin = process.env.CLOUDFLARED_BIN || path.join(
    __dirname,
    "..",
    "bin",
    process.platform === "win32" ? "cloudflared.exe" : "cloudflared",
);
```

or

```ts
export let bin = path.join(
    __dirname,
    "..",
    "bin",
    process.platform === "win32" ? "cloudflared.exe" : "cloudflared",
);

export function use(file: string) {
    bin = file;
}
```
